FROM node

WORKDIR /reactsimplecalc

COPY public/ /reactsimplecalc/public
COPY src/ /reactsimplecalc/src
COPY package.json /reactsimplecalc
COPY package-lock.json /reactsimplecalc

RUN npm install
EXPOSE 3000

CMD ["npm", "start"]
